# The overall format is standard TOML format, v0.5.0.
# The name of the mod loader type to load - for regular FML @Mod mods it should be javafml
modLoader="javafml" #mandatory

# A version range to match for said mod loader - for regular FML @Mod it will be the forge version
loaderVersion="[32,)" #mandatory
issueTrackerURL="https://github.com/Sinhika/SimpleOres2/issues"
logoFile="simple_ores.png"

[[mods]]
modId="simpleores"
version="${version}"
displayName="Simple Ores"
updateJSONURL="https://raw.githubusercontent.com/Sinhika/SimpleOres2/1.15-revised/update.json"
displayURL="http://minecraft.curseforge.com/projects/simpleores"
credits="AleXndrTheGr8st (original mod), Sinhika (maintenance, ports), Paint_Ninja (initial 1.15 port)."
authors="AleXndrTheGr8st, Sinhika, Paint_Ninja"
description='''
A simple ore mod, featuring 5 balanced ores: Copper, Tin, Mythril, Adamantium and Onyx. 
All except Onyx can be found in the overworld, while Onyx can be found only in the Nether.
Each ore has its own unique properties, armor and tool sets, and more.

Additional Credits: Emirhangg (Turkish translation), AzazEL3095 (Castillian Spanish), 
	Wanadi (Brazillian Portuguese), El-Limbo (Argentinian Spanish), fearheaven (French),
	burunduk (Ukrainian), Ruukas97 (Danish), Unknown (Spanish, Simplified Chinese, Traditional Chinese)
'''

[[dependencies.simpleores]] #optional
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.simpleores]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,]"
    ordering="NONE"
    side="BOTH"